### ISSUE TITLE
2021年1月份还能开源么，盼回复

### ISSUE THREAD

**Issue by free46000** [Kulsk/xquic#4]
2021年1月份还能开源么，现在已经1月的最后一个工作日了，盼回复

**Comment by Kulsk** [comment]
sorry that the opensource work will be delay to the April. we are already in the opensource flow, and there are still some issues to be solved

**Comment by free46000** [comment]
可以给个类似于内测版本或者beta版本，提前让我集成下，测试下易用和性能么？
