### ISSUE TITLE
啥时发布呢

### ISSUE THREAD

**Issue by ytanhaha** [Kulsk/xquic#6]
延期了多次了，以前说2020年底，后来说2021年1月，再后来4月，现在已经4月了。。。

**Comment by flyboyxiang** [comment]
后面是说4月，不知道啥时候发布

**Comment by free46000** [comment]
我也在等...

**Comment by Kulsk** [comment]
> 延期了多次了，以前说2020年底，后来说2021年1月，再后来4月，现在已经4月了。。。

这个月已经在走公司的开源流程了，这个过程会消耗1~2个月，需要处理法务、合规这些事项。。。
